spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ehr
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

app:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET}
        token-validity-in-seconds: ${JWT_TOKEN_VALIDITY}
  default:
    user:
      role: ADMIN

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.ehrblockchain: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.orm.connections.pooling: WARN