spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

app:
  security:
    authentication:
      jwt:
        base64-secret: ${JWT_SECRET}
        token-validity-in-seconds: ${JWT_TOKEN_VALIDITY}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

logging:
  level:
    ROOT: INFO
    com.ehrblockchain: INFO